config/routes.rb
Rails.application.routes.draw do

  resources :workers
  get 'm2w' => 'm2w#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  resources :users

  resources :carriers

  resources :rail_cars

  #post 'purchase_orders/connect' => 'purchase_orders#connect', as: :purchase_order_connect
  get 'purchase_orders/:id/select' => 'purchase_orders#select', as: :select_purchase_order
  resources :purchase_orders

  get 'vendors/:id/select' => 'vendors#select', as: :select_vendor
  resources :vendors

  #post 'trailers/connect_po' => 'trailers#connect_po', as: :trailer_connect_po
  #get 'trailers/:id/select' => 'trailers#select', as: :select_trailer
  resources :trailers

  resources :user_access_levels

  root 'm2w#index'
  get '*path' => redirect('/')

  match 'active'  => 'sessions#active',  via: :get

  match 'timeout' => 'sessions#timeout', via: :get





end

app/models/trailer.rb
class Trailer < ActiveRecord::Base
  require 'aws-sdk'
  require 'm2w.rb'
  belongs_to :purchase_order
  belongs_to :worker


  has_attached_file :doc,
                    :storage => :s3,
                    :bucket => ENV['S3_BUCKET_NAME'],
                    :s3_credentials => {
                      :bucket => ENV['S3_BUCKET_NAME'],
                      :access_key_id => ENV['AWS_ACCESS_KEY_ID'],
                      :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']
                    },
                    :s3_endpoint => "s3-us-west-1.amazonaws.com"

  Paperclip::Attachment.default_options[:url] = ':s3_domain_url'
  Paperclip::Attachment.default_options[:path] = '/:class/:attachment/:id/:filename'

  validates :trailer_nbr, presence: true, uniqueness: true
  validates :driver_name, presence: true
  validates :bol_nbr, presence: true
  validates_numericality_of :bol_nbr, :greater_than_or_equal_to => 10000000, :less_than_or_equal_to => 10000000000, :message =>  "needs to be between 8-10 digits"
  validates :weight_lbs, presence: true
  # check for max ton weight size which is 1000 tons
  validates_numericality_of :weight_lbs, :less_than_or_equal_to => 2204493, :message => "needs to be less or equal to 1000T"
  validates :time_in, date:  { before_or_equal_to: :time_out }
  before_save :calculate_weight_in_tons

  # Documents validations

  validates_attachment :doc,
       content_type: {content_type: ['text/plain',
                                      "image/jpeg",
                                      "image/jpg",
                                      "image/png",
                                      "application/pdf",
                                      "application/vnd.ms-excel",
                                      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                                      "application/msword",
                                      "application/vnd.openxmlformats-officedocument.wordprocessingml.document"]},
                       size: {less_than: 2.megabytes}

  # Explicitly do not Validate
  do_not_validate_attachment_file_type :doc

  before_post_process :doc

  def calculate_weight_in_tons
    self.weight_tons = cvt_lbs_to_tons(weight_lbs)
  end

end

app/controllers/trailers_controller.rb
class TrailersController < ApplicationController
  before_action :authorize
  before_action :set_trailer, only: [:show, :edit, :update, :destroy]
  require 'm2w.rb'
  #@purchaseorders = PurchaseOrder.list_for_select_po


  # GET /trailers
  # GET /trailers.json
  #@purchase_orders = PurchaseOrder.list_for_select_po
  def index
    @trailers = Trailer.all
  end


  # GET /trailers/1
  # GET /trailers/1.json
  def show
    @date_component= Time.diff(@trailer.time_out, @trailer.time_in,'%y, %M, %w, %d and %h:%m:%s')
    @trailer.time_taken_number = @date_component[:diff].to_s


    # load the PO information to display po #
    if @trailer.purchaseorder_id !=0
      @trailer_po = PurchaseOrder.find(@trailer.purchaseorder_id)
      @trailer_po_nf = false
    else
      # set to 0 for the Show screen
      @trailer_po_nf = true
    end

    # load the Carrier information for display
    if @trailer.carrier_id !=0
      @trailer_carrier = Carrier.find(@trailer.carrier_id )
      @trailer_carrier_nf = false
    else
      @trailer_carrier_nf = true
    end

    # load the Worker information for display
    if @trailer.badge_nbr !=0
      @trailer_worker = Worker.where(badge_nbr: @trailer.badge_nbr).take
      @trailer_worker_nf = false
   else
     @trailer_worker_nf = true
   end
  end



  # GET /trailers/new
  def new
    # load arrys for dropdown selection
    load_all_arrays

    @trailer_new = true
    @trailer = Trailer.new
    @prev_trailer_weight_lbs = -1
  end


  # GET /trailers/1/edit
  def edit
    if @trailer.purchaseorder_id !=0
      @trailer_new = false
      @prev_trailer_weight_lbs = @trailer.weight_lbs
    else
      @trailer_new = true
      @prev_trailer_weight_lbs = -1 # flag first time
    end


    # load arrays for drop down selections
    load_all_arrays

    @date_component= Time.diff(@trailer.time_out, @trailer.time_in,'%y, %M, %w, %d and %h:%m:%s')
    @trailer.time_taken_number = @date_component[:diff].to_s
  end

  # POST /trailers
  # POST /trailers.json
  def create
    load_all_arrays

    @trailer_new = true
    @trailer = Trailer.new(trailer_params)
    #@purchase_orders = PurchaseOrder.list_for_select_po
    @trailer.added_by = @user_full_name
    @trailer.changed_by = @user_full_name
    @prev_trailer_weight_lbs = -1

    respond_to do |format|
      if @trailer.save
        format.html { redirect_to @trailer, notice: 'Trailer was successfully created.' }
        format.json { render :show, status: :created, location: @trailer }
      else
        format.html { render :new }
        format.json { render json: @trailer.errors, status: :unprocessable_entity }
      end
      # update the PO remaing weight on the PO
      #puts"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb new trailer purchase id"
      #puts @trailer.purchaseorder_id.to_s
      @prev_trailer_weight_lbs = -1
      update_po_remaining_lbs(@trailer.purchaseorder_id, @prev_trailer_weight_lbs)
    end
  end

  # PATCH/PUT /trailers/1
  # PATCH/PUT /trailers/1.json
  def update
    @trailer.changed_by = @user_full_name
    # update purchase order remaining weight  less what is the weight on the trailer (tons)

    load_all_arrays


    respond_to do |format|
      # Calculate duration
      @date_component= Time.diff(@trailer.time_out, @trailer.time_in,'%y, %M, %w, %d and %h:%m:%s')
      @trailer.time_taken_number = @date_component[:diff].to_s
      if @trailer.purchaseorder_id == 0
        @prev_trailer_weight_lbs = -1 # case where PO was not previously assigned
      else
        @prev_trailer_weight_lbs = @trailer.weight_lbs
      end
      #puts "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww",@trailer.weight_lbs
      #@trailer.weight_tons = cvt_lbs_to_tons(@trailer.weight_lbs)

      if @trailer.update(trailer_params)
        format.html { redirect_to @trailer, notice: 'Trailer was successfully updated.' }
        format.json { render :show, status: :ok, location: @trailer }
      else
        format.html { render :edit }
        format.json { render json: @trailer.errors, status: :unprocessable_entity }
      end
      # update the PO remaing weight on the PO
      #puts"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb update trailer purchase id"
      #puts @trailer.purchaseorder_id.to_s

      update_po_remaining_lbs(@trailer.purchaseorder_id, @prev_trailer_weight_lbs)
    end
  end

  # DELETE /trailers/1
  # DELETE /trailers/1.json
  def destroy
    @trailer.destroy
    respond_to do |format|
      format.html { redirect_to trailers_url, notice: 'Trailer was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  # function to update remaining weight tons
  def update_po_remaining_lbs(po_id, prev_trailer_weight_lbs)
    #puts "****************************************in update po trailer purchase id"
    #puts po_id.to_s, prev_trailer_weight_lbs, @trailer.weight_lbs

    return if (po_id == 0 || prev_trailer_weight_lbs == @trailer.weight_lbs)  # exit if empty OR weight has not changed
    #puts "passed the test"

    prev_trailer_weight_lbs = 0 if prev_trailer_weight_lbs == -1

    if @purchase_order = PurchaseOrder.find(po_id)

      # user changed the weight in lbs..so lets add the previous verion to the PO and subtract the new weight value
       #puts "sssssssssssssssssssssssssssssssssssssssss purchase order found", po_id
       @remaining_lbs = @purchase_order.remaining_weight_lbs - @trailer.weight_lbs + prev_trailer_weight_lbs
       if @remaining_lbs >= 0
         @purchase_order.remaining_weight_lbs =  @remaining_lbs
         @purchase_order.remaining_weight_tons = cvt_lbs_to_tons(@remaining_lbs)
         #puts ".........................................po.remaining weight"
         #puts   @purchase_order.remaining_weight_tons, @purchase_order.remaining_weight_lbs,@purchase_order.po_nbr.to_s
         @purchase_order.save
         #puts "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx PO SAVED",po_id.to_s
       else
         puts "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"
         puts "Remaining Weight cannot be less than 0"
         #@purchase_order.remaining_weight_tons = 0
       end
     else
       puts "........................................."
       puts "purchase order not found",po_id
       format.html { render :edit }
       format.json { render json: @trailer.errors, status: :unprocessable_entity }
     end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trailer
      @trailer = Trailer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trailer_params
      params.require(:trailer).permit(:trailer_nbr, :driver_name, :carrier_id,
                                      :date_shipped, :bol_nbr, :time_in, :time_out,
                                      :time_taken_number, :railcar_nbr, :badge_nbr,
                                      :weight_lbs, :weight_tons, :purchaseorder_id,
                                      :doc, :doc_file_name, :doc_file_size,
                                      :doc_content_type, :doc_comment, :doc_updated_at
                                      )
    end
end

app/helpers/trailers_helper.rb
module TrailersHelper
end

app/views/trailers/_form.html.erb
<%= form_for(@trailer, html:{ multipart: true }) do |f| %>
  <% if @trailer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trailer.errors.count, "error") %> prohibited this trailer from being saved:</h2>

      <ul>
      <% @trailer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :trailer_nbr, "Trailer \#" %><br>
    <%= f.text_field :trailer_nbr %>
  </div>
  <div class="field">
    <%= f.label :driver_name, "Driver Name" %><br>
    <%= f.text_field :driver_name %>
  </div>
  <div class="field">
    <%= f.label :carrier_id, "Carrier Name" %><br>
    <%#= f.number_field :carrier_id %>
    <%= f.select(:carrier_id, options_for_select(@carrier_array)) %>
  </div>
  <div class="field">
    <%= f.label :date_shipped %><br>
    <%= f.date_select :date_shipped %>
  </div>
  <div class="field">
    <%= f.label :bol_nbr, "BOL \#" %><br>
    <%= f.number_field :bol_nbr %>
  </div>
  <div class="field">
    <%= f.label :time_in %><br>
    <%= f.datetime_select :time_in %>
  </div>
  <div class="field">
    <%= f.label :time_out %><br>
    <%= f.datetime_select :time_out %>
  </div>
  <div class="field">
    <%= f.label :time_taken_number, "Duration" %><br>
    <%= f.text_field :time_taken_number, disabled: true %>
  </div>
  <div class="field">
    <%= f.label :railcar_nbr, "Rail Car \#" %><br>
    <%#= f.text_field :railcar_nbr %>
    <% if !@trailer_new %>
      <%= f.select(:railcar_nbr, options_for_select(@rail_car_array,@trailer.badge_nbr)) %>
    <% else %>
      <%#= f.select(:purchaseorder_id, options_for_select(purchase_orders)) %>
      <%= f.select(:railcar_nbr, options_for_select(["Not Assigned"]+ @rail_car_array)) %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :badge_nbr, "Worker" %><br>
    <% if :badge_nbr !=0 %>
        <%= f.select(:badge_nbr, options_for_select(@worker_array)) %>
    <% else %>
        <%= f.select(:badge_nbr, options_for_select(["Not Assigned"]+ @worker_array)) %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :weight_lbs, "Weight Lbs" %><br>
    <%#= f.number_field number_with_delimiter(:weight_lbs) %>
    <%= f.number_field :weight_lbs %>
  </div>
  <div class="field">
    <%= f.label :purchase_order, "PO \#: " %>
      <%#= f.number_field :purchaseorder_id %>
    <% if !@trailer_new %>
      <%= f.select(:purchaseorder_id, options_for_select(@po_array)) %>
    <% else %>
      <%#= f.select(:purchaseorder_id, options_for_select(purchase_orders)) %>
      <%= f.select(:purchaseorder_id, options_for_select(["Not Assigned"]+ @po_array)) %>
    <% end %>
  </div>

  <fieldset>
    <legend>Uploaded Document</legend>
    <div class="field">
      <%= f.label :doc_file_name, "File Name: " %>
      <%= f.text_field :doc_file_name, :disabled => true %>
    </div>
    <div class="field">
      <%= f.label :doc, "Select New Document to Upload: " %>
      <%= f.file_field :doc %>
    </div>

    <div class="field">
      <%= f.label :doc_comment, "Comments:" %><br>
      <%= f.text_area :doc_comment %>
    </div>
  </fieldset>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trailers/edit.html.erb
<h1>Editing Trailer</h1>

<%= render partial: "form", :locals => {purchase_orders: @purchase_orders} %>

<%= link_to 'Show', @trailer %> |
<%= link_to 'Back', trailers_path %>

app/views/trailers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Trailers</h1>

<table>
  <thead>
    <tr>
      <th>Trailer #</th>
      <th>Driver</th>
      <th>Weight lbs</th>
      <th>Carrier id</th>
      <th>Date Shipped</th>
      <th>BOL #</th>
      <th>Time in</th>
      <th>Time out</th>
      <th>Duration</th>
      <th>Railcar #</th>
      <th>Worker Badge</th>

      <th>Purchase id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trailers.each do |trailer| %>
      <tr>
        <td><%= trailer.trailer_nbr %></td>
        <td><%= trailer.driver_name %></td>
        <td><%= number_with_delimiter(trailer.weight_lbs) %></td>
        <td><%= trailer.carrier_id %></td>
        <td><%= trailer.date_shipped %></td>
        <td><%= trailer.bol_nbr %></td>
        <td><%= trailer.time_in %></td>
        <td><%= trailer.time_out %></td>
        <td><%= trailer.time_taken_number %></td>
        <td><%= trailer.railcar_nbr %></td>
        <td><%= trailer.badge_nbr %></td>
        <td><%= trailer.purchaseorder_id %></td>

        <td><%= link_to 'Show', trailer %></td>
        <td><%= link_to 'Edit', edit_trailer_path(trailer) %></td>
        <td><%= link_to 'Delete', trailer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trailer', new_trailer_path %>
<br/>
<br/>

<%= link_to "Back to M2W Menu", m2w_path %>

app/views/trailers/new.html.erb
<h1>New Trailer</h1>

<%= render partial: "form", :locals => {purchase_orders: @purchase_orders} %>

<%= link_to 'Back', trailers_path %>

app/views/trailers/show.html.erb
<p id="notice"><%= notice %></p>

<h2> Trailer Details </h2>
<p>
  <strong>Trailer #:</strong>
  <%= @trailer.trailer_nbr %>
</p>

<p>
  <strong>Driver Name:</strong>
  <%= @trailer.driver_name %>
</p>

<p>
  <strong>Carrier Name:</strong>
  <%#= @trailer.carrier_id %>
  <% if @trailer_carrier_nf %>
     <%= "Carrier Not Found" %>
  <% else %>
     <%= @trailer_carrier.carrier_name %>
     <strong> Carrier Id: </strong>
     <%= @trailer_carrier.id %>
  <% end %>
</p>

<p>
  <strong>Date Shipped:</strong>
  <%= @trailer.date_shipped %>
</p>

<p>
  <strong>BOL #:</strong>
  <%= @trailer.bol_nbr %>
</p>

<p>
  <strong>Time in:</strong>
  <%= @trailer.time_in %>
</p>

<p>
  <strong>Time out:</strong>
  <%= @trailer.time_out %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @trailer.time_taken_number %>
</p>

<p>
  <strong>Rail Car #:</strong>
  <%= @trailer.railcar_nbr %>
</p>

<p>
  <strong>Worker Badge #:</strong>
  <%= @trailer.badge_nbr %>
  <strong>Full Name:</strong>
  <%= @trailer_worker.first_name %>
  <%= @trailer_worker.last_name %>
</p>
<p>
  <strong>Weight tons:</strong>
  <%= @trailer.weight_tons.round(2)  %>
</p>

<p>
  <strong>Weight lbs:</strong>
  <%=number_with_delimiter(@trailer.weight_lbs)%>
</p>


<p>
  <strong>Purchase Order #:</strong>
  <% if @trailer_po_nf %>
     <%= "Not Assigned" %>
  <% else %>
     <%= @trailer_po.po_nbr %>
     <strong> Po Id: </strong>
     <%= @trailer_po.id %>
  <% end %>
  <%#= @trailer.purchaseorder_id %>
</p>

<p>
  <strong>Added by:</strong>
  <%= @trailer.added_by %>
</p>

<p>
  <strong>Changed by:</strong>
  <%= @trailer.changed_by %>
</p>

<fieldset>
  <legend> <strong> Uploaded Document </strong></legend>
    <p>
      <strong>File Name: </strong>
        <%= @trailer.doc_file_name %>
    </p>
    <p>
      <strong>Content Type: </strong>
        <%= @trailer.doc_content_type %>
    </p>
    <p>
      <strong>File Size: </strong>
        <%= number_to_human_size(@trailer.doc_file_size) %>
    </p>
    <p>
      <strong>Updated On: </strong>
        <%= @trailer.doc_updated_at %>
    </p>
    <p>
      <strong>Comments: </strong>
        <%= @trailer.doc_comment %>
    </p>
    <p>
  <strong> View Document :</string>

  <h3>
    <%= link_to @trailer.doc.original_filename, @trailer.doc.url, :target => "_blank" if @trailer.doc?%>
  </h3>

  <p>
</fieldset>

<%= link_to 'Edit', edit_trailer_path(@trailer) %> |
<%= link_to 'Back', trailers_path %>