config/routes.rb
Rails.application.routes.draw do

  resources :workers
  get 'm2w' => 'm2w#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  resources :users

  resources :carriers

  resources :rail_cars

  #post 'purchase_orders/connect' => 'purchase_orders#connect', as: :purchase_order_connect
  get 'purchase_orders/:id/select' => 'purchase_orders#select', as: :select_purchase_order
  resources :purchase_orders

  get 'vendors/:id/select' => 'vendors#select', as: :select_vendor
  resources :vendors

  #post 'trailers/connect_po' => 'trailers#connect_po', as: :trailer_connect_po
  #get 'trailers/:id/select' => 'trailers#select', as: :select_trailer
  resources :trailers

  resources :user_access_levels

  root 'm2w#index'
  get '*path' => redirect('/')

  match 'active'  => 'sessions#active',  via: :get

  match 'timeout' => 'sessions#timeout', via: :get





end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
  has_many :purchase_orders
  has_many :rail_cars

  #validates_numericality_of :po_nbr, :greater_than_or_equal_to => 10000000, :less_than_or_equal_to => 10000000000, :message =>  "needs to be between 8-10 digits"

  def self.list_for_select
     self.all.map do |vendor|
        [vendor.vendor_name, vendor.id]
     end
  end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :authorize
  before_action :set_vendor, only: [:show, :edit, :update, :destroy]

  # GET /vendors
  # GET /vendors.json
  def index
    @vendors = Vendor.all
  end

  # GET /vendors/1
  # GET /vendors/1.json
  def show
  end

  # GET /vendors/new
  def new
    @vendor = Vendor.new
  end

  # GET /vendors/1/edit
  def edit
  end

  # POST /vendors
  # POST /vendors.json
  def create
    @vendor = Vendor.new(vendor_params)
    @vendor.added_by = @user_full_name
    @vendor.changed_by = @user_full_name
    respond_to do |format|
      if @vendor.save
        format.html { redirect_to @vendor, notice: 'Vendor was successfully created.' }
        format.json { render :show, status: :created, location: @vendor }
      else
        format.html { render :new }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendors/1
  # PATCH/PUT /vendors/1.json
  def update
    @vendor.changed_by = @user_full_name
    respond_to do |format|
    if @vendor.update(vendor_params)
        format.html { redirect_to @vendor, notice: 'Vendor was successfully updated.' }
        format.json { render :show, status: :ok, location: @vendor }
      else
        format.html { render :edit }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendors/1
  # DELETE /vendors/1.json
  def destroy
    @vendor.destroy
    respond_to do |format|
      format.html { redirect_to vendors_url, notice: 'Vendor was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def select
    @purchase_order_id = params[:id]
    @vendors = Vendor.list_for_select
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vendor
      @vendor = Vendor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vendor_params
      params.require(:vendor).permit(:vendor_name, :address_line_1, :address_line_2,
                                    :city_name, :state_code, :zip_code, :contact_name1,
                                    :email1, :phone_nbr1, :contact_name2, :email2, :phone_nbr2,
                                    :comments) #, :added_by, :changed_by)
    end
end

app/helpers/vendors_helper.rb
module VendorsHelper
  def us_states
      [
        ['Alabama', 'AL'],
        ['Alaska', 'AK'],
        ['Arizona', 'AZ'],
        ['Arkansas', 'AR'],
        ['California', 'CA'],
        ['Colorado', 'CO'],
        ['Connecticut', 'CT'],
        ['Delaware', 'DE'],
        ['District of Columbia', 'DC'],
        ['Florida', 'FL'],
        ['Georgia', 'GA'],
        ['Hawaii', 'HI'],
        ['Idaho', 'ID'],
        ['Illinois', 'IL'],
        ['Indiana', 'IN'],
        ['Iowa', 'IA'],
        ['Kansas', 'KS'],
        ['Kentucky', 'KY'],
        ['Louisiana', 'LA'],
        ['Maine', 'ME'],
        ['Maryland', 'MD'],
        ['Massachusetts', 'MA'],
        ['Michigan', 'MI'],
        ['Minnesota', 'MN'],
        ['Mississippi', 'MS'],
        ['Missouri', 'MO'],
        ['Montana', 'MT'],
        ['Nebraska', 'NE'],
        ['Nevada', 'NV'],
        ['New Hampshire', 'NH'],
        ['New Jersey', 'NJ'],
        ['New Mexico', 'NM'],
        ['New York', 'NY'],
        ['North Carolina', 'NC'],
        ['North Dakota', 'ND'],
        ['Ohio', 'OH'],
        ['Oklahoma', 'OK'],
        ['Oregon', 'OR'],
        ['Pennsylvania', 'PA'],
        ['Puerto Rico', 'PR'],
        ['Rhode Island', 'RI'],
        ['South Carolina', 'SC'],
        ['South Dakota', 'SD'],
        ['Tennessee', 'TN'],
        ['Texas', 'TX'],
        ['Utah', 'UT'],
        ['Vermont', 'VT'],
        ['Virginia', 'VA'],
        ['Washington', 'WA'],
        ['West Virginia', 'WV'],
        ['Wisconsin', 'WI'],
        ['Wyoming', 'WY']
      ]
  end
end

app/views/vendors/_form.html.erb
<%= form_for(@vendor) do |f| %>
  <% if @vendor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vendor.errors.count, "error") %> prohibited this vendor from being saved:</h2>

      <ul>
      <% @vendor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
    <%= f.label :vendor_name, "Vendor Name" %><br>
    <%= f.text_field :vendor_name %>
  </div>
  <div class="field">
    <%= f.label :address_line_1, "Address Line1" %><br>
    <%= f.text_field :address_line_1 %>
  </div>
  <div class="field">
    <%= f.label :address_line_2, "Address Line2" %><br>
    <%= f.text_field :address_line_2 %>
  </div>
  <div class="field">
    <%= f.label :city_name, "City" %><br>
    <%= f.text_field :city_name %>
  </div>
  <div class="field">
    <%= f.label :state_code, "State" %><br>
    <% if :state_code != nil %>
      <%= f.select(:state_code, options_for_select(us_states,@vendor.state_code)) %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :zip_code,"ZIP" %><br>
    <%= f.number_field :zip_code %>
  </div>
  <div class="field">
    <%= f.label :contact_name1,"Contacy Name1" %><br>
    <%= f.text_field :contact_name1 %>
  </div>
  <div class="field">
    <%= f.label :email1 %><br>
    <%= f.text_field :email1 %>
  </div>
  <div class="field">
    <%= f.label :phone_nbr1,"Phone \#" %><br>
    <%= f.text_field number_to_phone(:phone_nbr1) %>
  </div>
  <div class="field">
    <%= f.label :contact_name2, "Contact Name2" %><br>
    <%= f.text_field :contact_name2 %>
  </div>
  <div class="field">
    <%= f.label :email2 %><br>
    <%= f.text_field :email2 %>
  </div>
  <div class="field">
    <%= f.label :phone_nbr2,"Phone \#" %><br>
    <%= f.text_field number_to_phone(:phone_nbr2) %>
  </div>
  <div class="field">
    <%= f.label :comments %><br>
    <%= f.text_area :comments %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vendors/edit.html.erb
<h1>Editing Vendor</h1>

<%= render 'form' %>

<%= link_to 'Show', @vendor %> |
<%= link_to 'Back', vendors_path %>

app/views/vendors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Vendors</h1>

<table>
  <thead>
    <tr>
      <th>Vendor Name</th>
      <th>Address Line1</th>
      <th>Address Line2</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Contact Name</th>
      <th>Email</th>
      <th>Phone #</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vendors.each do |vendor| %>
      <tr>
        <td><%= vendor.vendor_name %></td>
        <td><%= vendor.address_line_1 %></td>
        <td><%= vendor.address_line_2 %></td>
        <td><%= vendor.city_name %></td>
        <td><%= vendor.state_code %></td>
        <td><%= vendor.zip_code %></td>
        <td><%= vendor.contact_name1 %></td>
        <td><%= vendor.email1 %></td>
        <td><%= vendor.phone_nbr1 %></td>


        <td><%= link_to 'Show', vendor %></td>
        <td><%= link_to 'Edit', edit_vendor_path(vendor) %></td>
        <td><%= link_to 'Delete', vendor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vendor', new_vendor_path %>
<br/>
<br/>

<%= link_to "Back to M2W Menu", m2w_path %>

app/views/vendors/new.html.erb
<h1>New Vendor</h1>

<%= render 'form' %>

<%= link_to 'Back', vendors_path %>

app/views/vendors/select.html.erb
<%= form_tag( purchase_order_connect_path, method: 'post') do %>
  <%= hidden_field_tag(:purchase_order_id, @purchase_order_id) %>
  Choose Vendor:
  <%= select_tag(:vendor_id, options_for_select(@vendors)) %>
  <%= submit_tag("Select") %>
<% end %>

app/views/vendors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Vendor Name:</strong>
  <%= @vendor.vendor_name %>
</p>

<p>
  <strong>Address Line1:</strong>
  <%= @vendor.address_line_1 %>
</p>

<p>
  <strong>Address Line2:</strong>
  <%= @vendor.address_line_2 %>
</p>

<p>
  <strong>City Name:</strong>
  <%= @vendor.city_name %>
</p>

<p>
  <strong>State:</strong>
  <%= @vendor.state_code %>
</p>

<p>
  <strong>ZIP:</strong>
  <%= @vendor.zip_code %>
</p>

<p>
  <strong>Contact Name1:</strong>
  <%= @vendor.contact_name1 %>
</p>

<p>
  <strong>Email1:</strong>
  <%= @vendor.email1 %>
</p>

<p>
  <strong>Phone #1:</strong>
  <%= number_to_phone(@vendor.phone_nbr1) %>
</p>

<p>
  <strong>Contact Name2:</strong>
  <%= @vendor.contact_name2 %>
</p>

<p>
  <strong>Email2:</strong>
  <%= @vendor.email2 %>
</p>

<p>
  <strong>Phone #2:</strong>
  <%= number_to_phone(@vendor.phone_nbr2) %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @vendor.comments %>
</p>

<p>
  <strong>Added by:</strong>
  <%= @vendor.added_by %>
</p>

<p>
  <strong>Changed by:</strong>
  <%= @vendor.changed_by %>
</p>

<p>
  <strong>Purchase Orders:</strong>
  <% @vendor.purchase_orders.each do |purchase_order| %>
    <p>
      PO #: <%= purchase_order.id %> <br/>
    </p>
    <% end %>
  </p>

<%= link_to 'Edit', edit_vendor_path(@vendor) %> |
<%= link_to 'Back', vendors_path %>