config/routes.rb
Rails.application.routes.draw do

  resources :workers
  get 'm2w' => 'm2w#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  resources :users

  resources :carriers

  resources :rail_cars

  #post 'purchase_orders/connect' => 'purchase_orders#connect', as: :purchase_order_connect
  get 'purchase_orders/:id/select' => 'purchase_orders#select', as: :select_purchase_order
  resources :purchase_orders

  get 'vendors/:id/select' => 'vendors#select', as: :select_vendor
  resources :vendors

  #post 'trailers/connect_po' => 'trailers#connect_po', as: :trailer_connect_po
  #get 'trailers/:id/select' => 'trailers#select', as: :select_trailer
  resources :trailers

  resources :user_access_levels

  root 'm2w#index'
  get '*path' => redirect('/')

  match 'active'  => 'sessions#active',  via: :get

  match 'timeout' => 'sessions#timeout', via: :get





end

app/models/worker.rb
class Worker < ActiveRecord::Base
  has_many :trailers

  validates :badge_nbr, presence: true, uniqueness: true
  validates :first_name,
            :last_name,
            :effective_date,
            :address_line_1,
            :city_name,
            :state_code,
            :zip_code,
            :email, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end

  def self.list_for_select_worker
     self.all.map do |worker|
        [worker.full_name, worker.badge_nbr]
     end
  end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_action :set_worker, only: [:show, :edit, :update, :destroy]

  # GET /workers
  # GET /workers.json
  def index
    @workers = Worker.all
  end

  # GET /workers/1
  # GET /workers/1.json
  def show
  end

  # GET /workers/new
  def new
    @worker = Worker.new
    @worker.active = true
  end

  # GET /workers/1/edit
  def edit
  end

  # POST /workers
  # POST /workers.json
  def create
    @worker = Worker.new(worker_params)
    @worker.added_by = @user_full_name
    @worker.changed_by = @user_full_name
    respond_to do |format|
      if @worker.save
        format.html { redirect_to @worker, notice: 'Worker was successfully created.' }
        format.json { render :show, status: :created, location: @worker }
      else
        format.html { render :new }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workers/1
  # PATCH/PUT /workers/1.json
  def update
    @worker.changed_by = @user_full_name
    respond_to do |format|
      if @worker.update(worker_params)
        format.html { redirect_to @worker, notice: 'Worker was successfully updated.' }
        format.json { render :show, status: :ok, location: @worker }
      else
        format.html { render :edit }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workers/1
  # DELETE /workers/1.json
  def destroy
    @worker.destroy
    respond_to do |format|
      format.html { redirect_to workers_url, notice: 'Worker was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_worker
      @worker = Worker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def worker_params
      params.require(:worker).permit(:badge_nbr, :effective_date, :active, :first_name, :last_name, :address_line_1, :address_line_2, :city_name, :state_code, :zip_code, :email, :added_by, :changed_by, :comments)
    end
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/workers/_form.html.erb
<%= form_for(@worker) do |f| %>
  <% if @worker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@worker.errors.count, "error") %> prohibited this worker from being saved:</h2>

      <ul>
      <% @worker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :badge_nbr, "Badge \#" %><br>
    <%= f.number_field :badge_nbr %>
  </div>
  <div class="field">
    <%= f.label :effective_date, "Effective Date" %><br>
    <%= f.date_select :effective_date %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :first_name, "First Name" %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name, "Last Name" %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :address_line_1, "Address line 1"%><br>
    <%= f.text_field :address_line_1 %>
  </div>
  <div class="field">
    <%= f.label :address_line_2, "Address Line 2" %><br>
    <%= f.text_field :address_line_2 %>
  </div>
  <div class="field">
    <%= f.label :city_name, "City" %><br>
    <%= f.text_field :city_name %>
  </div>
  <div class="field">
    <%= f.label :state_code, "State" %><br>
    <% if :state_code != nil %>
      <%= f.select(:state_code, options_for_select(us_states,@worker.state_code)) %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :zip_code, "ZIP" %><br>
    <%= f.number_field :zip_code %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :comments %><br>
    <%= f.text_area :comments %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/workers/edit.html.erb
<h1>Editing Worker</h1>

<%= render 'form' %>

<%= link_to 'Show', @worker %> |
<%= link_to 'Back', workers_path %>

app/views/workers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing of Workers</h1>

<table>
  <thead>
    <tr>
      <th>Badge #</th>
      <th>Effective date</th>
      <th>Active</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Address line 1</th>
      <th>Address line 2</th>
      <th>City name</th>
      <th>State</th>
      <th>ZIP</th>
      <th>Email</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @workers.each do |worker| %>
      <tr>
        <td><%= worker.badge_nbr %></td>
        <td><%= worker.effective_date %></td>
        <td><%= worker.active %></td>
        <td><%= worker.first_name %></td>
        <td><%= worker.last_name %></td>
        <td><%= worker.address_line_1 %></td>
        <td><%= worker.address_line_2 %></td>
        <td><%= worker.city_name %></td>
        <td><%= worker.state_code %></td>
        <td><%= worker.zip_code %></td>
        <td><%= worker.email %></td>

        <td><%= link_to 'Show', worker %></td>
        <td><%= link_to 'Edit', edit_worker_path(worker) %></td>
        <td><%= link_to 'Delete', worker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Worker', new_worker_path %>

<br/>
<br/>

<%= link_to "Back to M2W Menu", m2w_path %>

app/views/workers/new.html.erb
<h1>New Worker</h1>

<%= render 'form' %>

<%= link_to 'Back', workers_path %>

app/views/workers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Badge #:</strong>
  <%= @worker.badge_nbr %>
</p>

<p>
  <strong>Effective Date:</strong>
  <%= @worker.effective_date %>
</p>

<p>
  <strong>Active:</strong>
  <%= @worker.active %>
</p>

<p>
  <strong>First Name:</strong>
  <%= @worker.first_name %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @worker.last_name %>
</p>

<p>
  <strong>Address line 1:</strong>
  <%= @worker.address_line_1 %>
</p>

<p>
  <strong>Address line 2:</strong>
  <%= @worker.address_line_2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @worker.city_name %>
</p>

<p>
  <strong>State:</strong>
  <%= @worker.state_code %>
</p>

<p>
  <strong>ZIP:</strong>
  <%= @worker.zip_code %>
</p>

<p>
  <strong>Email:</strong>
  <%= @worker.email %>
</p>

<p>
  <strong>Added by:</strong>
  <%= @worker.added_by %>
</p>

<p>
  <strong>Changed by:</strong>
  <%= @worker.changed_by %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @worker.comments %>
</p>

<%= link_to 'Edit', edit_worker_path(@worker) %> |
<%= link_to 'Back', workers_path %>