config/routes.rb
Rails.application.routes.draw do

  resources :workers
  get 'm2w' => 'm2w#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  resources :users

  resources :carriers

  resources :rail_cars

  #post 'purchase_orders/connect' => 'purchase_orders#connect', as: :purchase_order_connect
  get 'purchase_orders/:id/select' => 'purchase_orders#select', as: :select_purchase_order
  resources :purchase_orders

  get 'vendors/:id/select' => 'vendors#select', as: :select_vendor
  resources :vendors

  #post 'trailers/connect_po' => 'trailers#connect_po', as: :trailer_connect_po
  #get 'trailers/:id/select' => 'trailers#select', as: :select_trailer
  resources :trailers

  resources :user_access_levels

  root 'm2w#index'
  get '*path' => redirect('/')

  match 'active'  => 'sessions#active',  via: :get

  match 'timeout' => 'sessions#timeout', via: :get





end

app/controllers/m2w_controller.rb
class M2wController < ApplicationController
before_action :authorize

  def index
  end
end

app/views/m2w/index.html.erb
<br>
<h1>M2W Admin Functions</h1>
<h3>
  <%= "User: #{@user_full_name}  Date: #{Date.current.to_s} " %>
</h3>
<body>
  <ul>
    <li>
      <%= link_to 'Carriers', carriers_path %>
    </li>
  </ul>
  <ul>
    <li>
      <%= link_to 'Purchase Orders', purchase_orders_path %>
    </li>
  </ul>
  <ul>
    <li>
      <%= link_to 'Rail Car', rail_cars_path %>
    </li>
  </ul>
  <ul>
    <li>
      <%= link_to 'Trailer', trailers_path %>
    </li>
  </ul>
  <ul>
    <li>
      <%= link_to 'Users', users_path %>
    </li>
  </ul>
  <ul>
    <li>
      <%= link_to 'User Access', user_access_levels_path %>
    </li>
  </ul>
  <ul>
    <li>
      <%= link_to 'Vendors', vendors_path %>
    </li>
  </ul>
  <ul>
    <li>
      <%= link_to 'Workers', workers_path %>
    </li>
  </ul>
        <br><br>
        <%= button_to 'Logout', logout_path, method: :delete %>
      </br>





<%= yield %>